version: '3'

services:
  node:
    image: node:8.16.0-alpine
    ports:
      - "8080:8080"
    volumes:
      - app-data:/front
    command: /bin/sh -c "cd /front && npm install && npm run serve"

volumes:
  app-data:
    driver_opts:
      type: none
      device: $PWD/front
      o: bind
